### ISSUE TITLE
Data set retrieve problem when any pv had problem during taking snapshot

### ISSUE THREAD

**Issue by shengb** [frib-high-level-controls/save-set-restore#13]
If there was any pv not connected during taking snapshot, the CS-Studio can not get saved data set back.

"""
An internal error occurred during: "Save and Restore: Load snapshot data".
java.lang.NullPointerException
"""

**Comment by jbobnar** [comment]
Please, provide the entire exception stack trace, because it does not happen to me.

**Comment by shengb** [comment]
I am using Eric's distribution, and unfortunately, there is no exception stack trace available in any console.
Here is an easy way to reproduce it:
1. Using MASAR to take a snapshot with a few PVs not available, which the values would be NULL;
2. Try to retrieve the same snapshot, which would give you the error.

If you like, I can send you example database offline.

**Comment by berryma4** [comment]
Do you see anything if you open a console?

**Comment by shengb** [comment]
OK, now I switched to linux terminal, and here is the output:
2016-02-17 09:07:15.297 SEVERE [Thread 21] org.csstudio.logging.PluginLogListener (logging) - An internal error occurred during: "Save and Restore: Load snapshot data".
java.lang.NullPointerException
	at gov.aps.jca.ValuedEnum.isEqualTo(ValuedEnum.java:34)
	at org.csstudio.saverestore.masar.MasarUtilities.fromEpics(MasarUtilities.java:260)
	at org.csstudio.saverestore.masar.MasarUtilities.resultToVSnapshot(MasarUtilities.java:243)
	at org.csstudio.saverestore.masar.MasarClient.loadSnapshotData(MasarClient.java:463)
	at org.csstudio.saverestore.masar.MasarDataProvider.getSnapshotContent(MasarDataProvider.java:258)
	at org.csstudio.saverestore.ui.ActionManager.loadSnapshot(ActionManager.java:77)
	at org.csstudio.saverestore.ui.ActionManager.lambda$1(ActionManager.java:89)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:52)
	at org.csstudio.saverestore.SaveRestoreService$SaveRestoreJob.run(SaveRestoreService.java:87)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by jbobnar** [comment]
I fixed this exception. The cause was that masar sent a severity code that is unknown to epics.
