### ISSUE TITLE
NPE w/ Tag Snapshot and Save Beamline Set

### ISSUE THREAD

**Issue by crispd** [frib-high-level-controls/save-set-restore#6]
What am I doing wrong? Is this something I should ignore?
I see the Beamline Set for the intended species in the Save & Restore Browser...

2015-12-02 12:29:04.068 SEVERE [Thread 124] org.csstudio.logging.PluginLogListener (logging) - An internal error occurred during: "Save and Restore: Tag Snapshot".
java.lang.NullPointerException
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:419)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:383)
	at org.csstudio.saverestore.git.GitManager.getCommitFromRevision(GitManager.java:1022)
	at org.csstudio.saverestore.git.GitManager.tagSnapshot(GitManager.java:834)
	at org.csstudio.saverestore.git.GitDataProvider.tagSnapshot(GitDataProvider.java:292)
	at org.csstudio.saverestore.ui.browser.ActionManager.lambda$1(ActionManager.java:115)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:52)
	at org.csstudio.saverestore.SaveRestoreService$2.run(SaveRestoreService.java:206)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

2015-12-02 12:34:15.975 SEVERE [Thread 197] org.csstudio.logging.PluginLogListener (logging) - An internal error occurred during: "Save and Restore: Save Beamline Set".
java.lang.NullPointerException
	at org.csstudio.saverestore.ui.Selector$1.beamlineSaved(Selector.java:142)
	at org.csstudio.saverestore.git.GitDataProvider.saveBeamlineSet(GitDataProvider.java:223)
	at org.csstudio.saverestore.ui.BeamlineSetController.lambda$1(BeamlineSetController.java:51)
	at java.util.Optional.map(Unknown Source)
	at org.csstudio.saverestore.ui.BeamlineSetController.save(BeamlineSetController.java:47)
	at org.csstudio.saverestore.ui.BeamlineSetEditor.lambda$8(BeamlineSetEditor.java:116)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:52)
	at org.csstudio.saverestore.SaveRestoreService$2.run(SaveRestoreService.java:206)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by crispd** [comment]
I can even make a snapshot, but I can't tag the snapshot

**Comment by berryma4** [comment]
Let's wait until the meeting on Thursday (tomorrow), so Jaka can explain his work and where he is currently.  This is not a release of the save restore program, but more of a good time to start making comments on functionalities and requirements.

**Comment by crispd** [comment]
That's fine with me. Guess I wasn't sure how much and what feedback was being asked for at this point. Looking forward to tomorrow.

**Comment by jbobnar** [comment]
Sorry for this. It is a bug that I discovered only two days ago. 
If you create a snapshot, immediately followed by a tag, it breaks. If after creating the snapshot you navigate to some other beamline set and then return and make the tag, it works OK. I will fix this.

**Comment by crispd** [comment]
That's fine, I'm not expecting everything to be polished, just conveying observed issues. You're right too, I can make a tag after having navigated to another set.

**Comment by jbobnar** [comment]
This was fixed a while ago.
